import { NextResponse } from "next/server"
import { prisma } from "@/lib/db"
import { requireOrgAccess } from "@/lib/auth"

export async function GET(
  req: Request,
  { params }: { params: { orgSlug: string; reportId: string } }
) {
  try {
    await requireOrgAccess(params.orgSlug)

    const organization = await prisma.organization.findUnique({
      where: { slug: params.orgSlug },
      select: { id: true, name: true },
    })

    if (!organization) {
      return NextResponse.json(
        { error: "Organization not found" },
        { status: 404 }
      )
    }

    const report = await prisma.report.findFirst({
      where: {
        id: params.reportId,
        organizationId: organization.id,
      },
      include: {
        generator: {
          select: {
            name: true,
            email: true,
          },
        },
      },
    })

    if (!report) {
      return NextResponse.json(
        { error: "Report not found" },
        { status: 404 }
      )
    }

    const csvContent = generateReportCSV(report)

    return new NextResponse(csvContent, {
      headers: {
        "Content-Type": "text/csv",
        "Content-Disposition": `attachment; filename="report-${report.id}.csv"`,
      },
    })
  } catch (error) {
    console.error("Error downloading report:", error)
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    )
  }
}

function generateReportCSV(report: any): string {
  let csv = `Report: ${report.title}\n`
  csv += `Type: ${report.type}\n`
  csv += `Generated: ${new Date(report.generatedAt).toLocaleString()}\n`
  csv += `Generated by: ${report.generator.name} (${report.generator.email})\n\n`

  if (report.type === "MEMBERSHIP_GROWTH" && report.data.monthlyGrowth) {
    csv += "Month,Total Members,Admins,Owners,Members,Active,Pending,Banned\n"
    for (const [month, data] of Object.entries(report.data.monthlyGrowth) as any) {
      csv += `${month},${data.total},${data.byRole.ORG_ADMIN || 0},${data.byRole.ORG_OWNER || 0},${data.byRole.MEMBER || 0},${data.byStatus.ACTIVE || 0},${data.byStatus.PENDING || 0},${data.byStatus.BANNED || 0}\n`
    }
  } else if (report.type === "EVENT_ATTENDANCE" && report.data.events) {
    csv += "Event Title,Start Date,Total RSVPs,Confirmed,Attended,Attendance Rate (%)\n"
    for (const event of report.data.events) {
      csv += `"${event.title}",${new Date(event.startDate).toLocaleDateString()},${event.totalRSVPs},${event.confirmedRSVPs},${event.attended},${event.attendanceRate.toFixed(2)}\n`
    }
  } else if (report.type === "REVENUE_ANALYSIS" && report.data.monthlyRevenue) {
    csv += "Month,Total Revenue,Tickets Revenue,Other Revenue\n"
    for (const [month, data] of Object.entries(report.data.monthlyRevenue) as any) {
      csv += `${month},${data.total},${data.tickets},${data.other}\n`
    }
  } else if (report.type === "TICKET_SALES" && report.data.ticketSales) {
    csv += "Ticket Name,Quantity Sold,Revenue\n"
    for (const ticket of report.data.ticketSales) {
      csv += `"${ticket.name}",${ticket.quantity},${ticket.revenue}\n`
    }
  }

  return csv
}